#-------------------------------
# General Site Settings

title: Eric Sartorius
description: "Designer . Developer . Linguist"
email: ericssartorius@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About, url: '#about-me'}
- {name: Projects, url: '#work'}
- {name: Contact, url: '#contact'}

lang-menu:
- {name: "<p>EN</p>", class: 'en lang-selected' }
- {name: "<p>日</p>", class: 'jp' }
- {name: "<p>한</p>", class: 'kr'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'A homepage for Eric "Epic" Sartorius.'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: UA-71581610-1

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurbEN: >
  **I love web design and frontend development** and do everything I can to improve my design and coding skills daily.
   Recently, I have finished frontend programs from both [Bloc,](https://www.bloc.io/frontend-development-bootcamp){:target="_blank"} an intensive online coding bootcamp, and [Free Code Camp](https://www.freecodecamp.com/ericssartorius){:target="_blank"}, another online frontend course.
   These days however, I spend most of my time studying new frontend technologies or working on [U-Judge](https://ujudge.meteor.com){:target="_blank"}, a universal online judging system. 

   
  Oh yeah, and web development isn't the only thing that I do. Living for 4 years in Japan and 5 years in Korea, I have done everything from teaching English and modeling to subtitling movies and even running the judging system for [R16](http://www.r16korea.com/?lang=en){:target="_blank"}, the world's largest breakdance competition.
  I also have a passion for calisthenics and I am a member of [Bar Kingz](https://www.facebook.com/barkingzkorea/){:target="_blank"}, a street workout team based in Seoul, South Korea. I am always hard at work either studying or exercising but loving every minute of it.


  For a detailed list of my professional experience, find me on [Linkedin](http://www.linkedin.com/in/ericsartorius){:target="_blank"} or [email me](#contact){:target="_blank"} for a copy of my resume.
   Also feel free to look at some of my projects below which I made during my time at [Bloc](https://www.bloc.io/frontend-development-bootcamp){:target="_blank"} and [Free Code Camp](https://www.freecodecamp.com/ericssartorius){:target="_blank"}. All of my code can be found on [Github](https://github.com/ericssartorius){:target="_blank"} or you can view my mini-projects on [Codepen.](https://codepen.com/ericssartorius){:target="_blank"}

blurbJP: >
  **ウェブデザインとフロントエンドプログラミングが大好きです。**毎日一所懸命デザインとコーディングの才能を上達するよう努力しています。
  ９年間海外に滞在したんですが（日本４年間、韓国５年間）、その間、英語教師、モデル、イベントプロダクション、アーティストブッキング、字幕作りなどの仕事をしました。
  [**R16**](http://www.r16korea.com/?lang=en){:target="_blank"}という世界で一番大きいなブレイクダンス大会でジャッジシステムの管理までしました。
  体操も大好きで、現在[**Bar Kingz**](https://www.facebook.com/barkingzkorea/){:target="_blank"}という韓国の運動パフォーマンスチームに入っています。


  最近[**Bloc**](https://www.bloc.io/frontend-development-bootcamp){:target="_blank"}というオンラインコーディングブートキャンプから卒業して、ウェブデザインの仕事をするためにアメリカに引っ越しました。
  もし共通の趣味があり、もしくは一緒に仕事をすることに興味があれば、是非[連絡してください!](#contact){:target="_blank"}

blurbKR: >
  **웹디자인과 프런트엔드 프로그래밍을 너무 좋아해요.** 매일 열심히 디자인과 코딩의 재능을 향상하기 위해 노력하고 있어요.
  9 년 동안 해외에 체류 했는데(일본 4 년, 한국 5 년), 그때 영어교사, 모델, 이벤트 프로덕션, 자막 제작 등의 작업을 했어요. 
  [**R16**](http://www.r16korea.com/?lang=en){:target="_blank"}이라는 세계에서 가장 큰 비보이 대회에서 사용하는 심판 시스템의 관리도 한 적이 있어요.
  체조도 너무 좋아하고, 현재 [**바킹즈**](https://www.facebook.com/barkingzkorea/){:target="_blank"}라는 길거리운동 팀에 속해 있습니다.
  

  요즘 [**Bloc**](https://www.bloc.io/frontend-development-bootcamp){:target="_blank"}라는 온라인 코딩 부트 캠프를 졸업해서  웹디자인 일을 하기위해 미국으로 이사했어요.
  만약 공통의 취미가 있고, 혹은 함께 일을 하는 것에 관심이 있다면 꼭[**연락하십시오!**](#contact){:target="_blank"}
  

# skills:
# - {name: Communication, value: '9'}
# - {name: Organization, value: '7'}
# - {name: Learning, value: '10'}
# - {name: Teaching, value: '6'}
# - {name: Planning, value: '7'}
# - {name: Visual Design, value: '5'}
# - {name: UX Design, value: '8'}
# - {name: Programming, value: '6'}

#-------------------------------
# Work Section

projects:
- {name: U-Judge, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Bloc Time, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Bloc Pong, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Bloc Jams, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Google Simon, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Tic Tac Toe, folder: 'proj-6', file: 'work/proj-6.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'https://github.com/ericssartorius'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/ericsartorius/'}
- {icon: 'twitter', link: 'http://twitter.com/ericssartorius'}
- {icon: 'facebook', link: 'https://facebook.com/iamtheepic'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
